### ISSUE TITLE
[BUG] [ws-version-checker] Does not download latest unified agent

### ISSUE THREAD

**Issue by samq-ws** [whitesource-ps/ws-version-checker#6]
**Bug Description**  
The newest version of the unified agent is not downloaded if using environment variables.

**Steps to Reproduce**  
Using an ubuntu-latest docker container you can reproduce easily with the following commands

*Container Setup*
```
docker run --name pstools -i -d ubuntu:latest
docker exec -it pstools bash
apt update
export DEBIAN_FRONTEND=noninteractive
apt install -y git jq nano curl python3 python3-pip openjdk-8-jdk
```
*Test*
```
curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent-21.7.1.jar
git clone https://github.com/whitesource-ps/ws-version-checker.git && cd ./ws-version-checker
pip install -r requirements.txt
cd ./version_check
export WSVC_FILE_DIR=../../   
export WSVC_FILE_NAME=$(basename $(find $WSVC_FILE_DIR -type f -name "wss-unified-agent*.jar"))
python3 ./ws_version_checker.py
```
*Verification*
```
ls ../../
```

**Expected Behavior**  
The tool should download the latest version of the unified agent

**Screenshots**  

**Environment Details**  
 - OS: Ubuntu-latest

**Additional Context**

**Comment by rammatzkvosky** [comment]
Hi @samq-ws .

I reproduced the issue you reported about with the same steps you provided and did not face any issue .

See attached caption and [output.txt](https://github.com/whitesource-ps/ws-version-checker/files/7273044/output.txt) log : 

![log](https://user-images.githubusercontent.com/41573396/135747552-4fbc117e-05a2-4eb6-92e9-663775d91162.jpg)

The `WSVC_FILE_NAME` input will be also applicable to the new version downloaded jar - using specific version with the agent jar name is not recommended  ( in Whitesource scan step ) and the [](https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar) is more [relevant](https://whitesource.atlassian.net/wiki/spaces/WD/pages/1140852201/Getting+Started+with+the+Unified+Agent#Downloading-the-Unified-Agent).

Having said that , we might consider adding support for dynamic file name in one of the next versions.

**Comment by samq-ws** [comment]
@rammatzkvosky Please run ```ls ../../``` after running the above scripts to see that even though the console log says it downloaded the new unified agent...it does not.

**Comment by rammatzkvosky** [comment]
Hi @samq-ws ,

See attached screen capture - The jar name is kept the same (this is how it was designed ) but the version was updated : 

![image](https://user-images.githubusercontent.com/41573396/135878226-1b4fe679-3511-4303-b992-2b6e93d0f3de.png)


Full log [ attached ](https://github.com/whitesource-ps/ws-version-checker/files/7279211/output_20211004.txt)

**Comment by samq-ws** [comment]
@rammatzkvosky Seems a bit confusing if a customer is using the default files names provided by the [WhiteSource download page](https://whitesource.atlassian.net/wiki/spaces/WD/pages/1140852201/Getting+Started+with+the+Unified+Agent#Downloading-the-Unified-Agent).
